import { defineConfig } from 'wxt';
import tailwindcss from '@tailwindcss/vite';

// Public key of the extension's signing pair (~/.dayflow/extension-key.pem stays out of the repo). It pins the
// extension id to jagkpbdiempedibinmfafamdhnogognn, which the Google OAuth client is registered against.
// It belongs in DEV/unpacked builds only: the Chrome Web Store assigns the id itself and rejects (or silently
// re-keys) a package that ships "key". `DAYFLOW_STORE_BUILD=1 pnpm zip:store` therefore omits it.
const EXTENSION_PUBLIC_KEY =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6TqRPFlEsVJRB1n3pm2GGgE2txWcwUypIR1Q3TAtOSAXb6usnhTqGJCkygqG654hmOktAKKKQR8xbVuWkTOpqYpUVpHuk9zIzgYahVO1ZRVCjB6TQgk03vb++/3IqUm7ZSZP865B06YOUPs6aS6UekFXh/6mN9pcZyC1V01nJQmJX1Uh1UOmSdQZV0yzi1+bwZR4zAFJkKUKqvSFHVLIrfxEWh9VgenSm1xwLp6UEVcADgjwJnvUXILfQLU7eQV7J6rPMUuG4jGq4eqU1gHzHv1ZEqUVkoY8awWQeWeqhOve8WtO33fNV3ls/HdisKzZR6QDkcKD25OA37PT8eYkrQIDAQAB';

const STORE_BUILD = process.env.DAYFLOW_STORE_BUILD === '1';

// https://wxt.dev/api/config.html
export default defineConfig({
  modules: ['@wxt-dev/module-react'],
  vite: () => ({ plugins: [tailwindcss()] }),
  // Function form: .env files are loaded before it runs, so VITE_GOOGLE_CLIENT_ID is available.
  manifest: () => ({
    name: 'Dayflow Agent',
    // ≤132 chars: the Chrome Web Store shows this string as the short description on the item card
    // (docs/store/listing.md keeps the same text).
    description: 'A universal browser agent on Gemini: skills, site profiles and permissions you own. Default pack: KBTU student ops.',
    version: '0.2.0',
    minimum_chrome_version: '116',
    // Generated by docs/store/scripts/make-icons.mjs (pnpm icons) into public/icon/.
    icons: { 16: 'icon/16.png', 32: 'icon/32.png', 48: 'icon/48.png', 96: 'icon/96.png', 128: 'icon/128.png' },
    ...(STORE_BUILD ? {} : { key: EXTENSION_PUBLIC_KEY }),
    permissions: ['storage', 'alarms', 'sidePanel', 'tabs', 'scripting', 'downloads', 'notifications', 'webNavigation', 'activeTab', 'identity'],
    host_permissions: ['<all_urls>'],
    // client_id comes from extension/.env (VITE_GOOGLE_CLIENT_ID) at build time; the value is never logged.
    // Unset → the panel says "Drive not configured" and the vault falls back to the brain (src/agent/identity.ts).
    oauth2: {
      client_id: import.meta.env.VITE_GOOGLE_CLIENT_ID || 'unset.apps.googleusercontent.com',
      scopes: ['https://www.googleapis.com/auth/drive.file'],
    },
    action: {
      default_title: 'Dayflow — open the agent panel',
      default_icon: { 16: 'icon/16.png', 32: 'icon/32.png', 48: 'icon/48.png', 128: 'icon/128.png' },
    },
  }),
});
