"""Pitch-deck tool (PLAN v2 scene 6).

`build_deck(title, outline)` renders a real 16:9 PowerPoint file with python-pptx — a title slide plus one
slide per outline section (so an 8-section outline is a 9-slide deck) — and an HTML preview of the same
slides. The preview goes into the PageStore (kind=deck, served at GET /pages/deck/{id}); the .pptx bytes go
into the same blob store under `pages/deck/{id}.pptx` and are served at GET /pages/deck/{id}.pptx
(dayflow/api/deck_routes.py). Both URLs are unguessable (the PageStore's 128-bit id) and need no auth, so
the extension can `download(url=pptx_url, path=...)` the deck into the vault and `open_tab(preview_url)`
for the user.

Model input is defensive on purpose: Gemini writes the outline, so a section may arrive as a bare string,
name its heading "title", or pass bullets as one newline-separated string — all of that is normalised here
instead of failing the run.
"""

from __future__ import annotations

import html
import io
from typing import Any

from pptx import Presentation
from pptx.util import Emu, Inches, Length, Pt
from pydantic import BaseModel, Field, ValidationError

from dayflow.core.pages import PageStore, default_pages

PPTX_MIME = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
SLIDE_W = Inches(13.333)  # 16:9
SLIDE_H = Inches(7.5)
MIN_SECTIONS = 5  # + the title slide = the 6 slides the deck must have at minimum
MAX_SECTIONS = 24
MAX_BULLETS = 8
MAX_BULLET_CHARS = 220
COVER_FALLBACK = "Generated by Dayflow"

HEADING_KEYS = ("heading", "title", "name", "header")
BULLET_KEYS = ("bullets", "points", "content", "body", "items", "lines")
NOTES_KEYS = ("notes", "speaker_notes", "note")


class DeckSection(BaseModel):
    heading: str = Field(description="Slide heading, e.g. 'Problem'.")
    bullets: list[str] = Field(default_factory=list, description="2–5 short bullets.")
    notes: str = Field(default="", description="Optional speaker notes for this slide.")


def _as_bullets(raw: Any) -> list[str]:
    """A bullet list from whatever the model sent: a list, a newline/semicolon-separated string, or nothing."""
    items: list[Any]
    if raw is None:
        items = []
    elif isinstance(raw, str):
        items = [line for line in raw.replace(";", "\n").splitlines()]
    elif isinstance(raw, (list, tuple)):
        items = list(raw)
    else:
        items = [raw]
    out: list[str] = []
    for item in items:
        text = " ".join(str(item).strip().lstrip("-•*·").strip().split())
        if text:
            out.append(text[:MAX_BULLET_CHARS])
    return out[:MAX_BULLETS]


def normalize_section(raw: Any) -> DeckSection:
    """One outline entry → DeckSection. Accepts {'heading'|'title'|…} and bullets under several key names."""
    if isinstance(raw, str):
        return DeckSection(heading=" ".join(raw.split()))
    if not isinstance(raw, dict):
        raise ValueError(
            f"outline entries must be objects like {{'heading': ..., 'bullets': [...]}}, got {type(raw).__name__}"
        )
    lowered = {str(k).strip().lower(): v for k, v in raw.items()}
    heading = next((str(lowered[k]).strip() for k in HEADING_KEYS if str(lowered.get(k) or "").strip()), "")
    if not heading:
        raise ValueError(f"an outline entry has no heading (keys: {sorted(lowered)})")
    bullets = next((_as_bullets(lowered[k]) for k in BULLET_KEYS if lowered.get(k)), [])
    notes = next((str(lowered[k]).strip() for k in NOTES_KEYS if str(lowered.get(k) or "").strip()), "")
    return DeckSection(heading=" ".join(heading.split()), bullets=bullets, notes=notes)


def normalize_outline(outline: list[Any]) -> list[DeckSection]:
    return [normalize_section(entry) for entry in outline]


# ---------- pptx ----------


def _place(shape: Any, left: Length, top: Length, width: Length, height: Length) -> None:
    """The stock 4:3 template's placeholders sit in the wrong place on a 16:9 canvas; re-lay them out."""
    shape.left, shape.top, shape.width, shape.height = left, top, width, height


def _style(shape: Any, size: int, bold: bool = False) -> None:
    for para in shape.text_frame.paragraphs:
        para.font.size = Pt(size)
        para.font.bold = bold


def _placeholder(slide: Any, idx: int) -> Any:
    return next((ph for ph in slide.placeholders if ph.placeholder_format.idx == idx), None)


def build_pptx(title: str, subtitle: str, sections: list[DeckSection]) -> bytes:
    """A 16:9 .pptx: title slide + one bulleted slide per section. Returns the file bytes."""
    prs = Presentation()
    prs.slide_width, prs.slide_height = SLIDE_W, SLIDE_H
    margin = Inches(0.9)
    width = Emu(int(SLIDE_W) - 2 * int(margin))

    cover: Any = prs.slides.add_slide(prs.slide_layouts[0])
    if cover.shapes.title is not None:
        cover.shapes.title.text = title
        _place(cover.shapes.title, margin, Inches(2.3), width, Inches(1.8))
        _style(cover.shapes.title, 44, bold=True)
    if (sub := _placeholder(cover, 1)) is not None:
        sub.text_frame.text = subtitle or COVER_FALLBACK
        _place(sub, margin, Inches(4.2), width, Inches(1.0))
        _style(sub, 20)

    for section in sections:
        slide: Any = prs.slides.add_slide(prs.slide_layouts[1])
        if slide.shapes.title is not None:
            slide.shapes.title.text = section.heading
            _place(slide.shapes.title, margin, Inches(0.6), width, Inches(1.1))
            _style(slide.shapes.title, 32, bold=True)
        if (body := _placeholder(slide, 1)) is not None:
            _place(body, margin, Inches(1.9), width, Inches(4.8))
            frame = body.text_frame
            frame.word_wrap = True
            for i, bullet in enumerate(section.bullets or [section.heading]):
                para = frame.paragraphs[0] if i == 0 else frame.add_paragraph()
                para.text = bullet
                para.level = 0
                para.font.size = Pt(20)
        if section.notes:
            slide.notes_slide.notes_text_frame.text = section.notes

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ---------- preview ----------


def render_preview_html(title: str, subtitle: str, sections: list[DeckSection], pptx_url: str) -> str:
    """The same slides as an HTML page (16:9 cards) with a download link to the .pptx."""
    esc = html.escape
    cards: list[str] = [
        '<section class="slide cover">'
        f"<h1>{esc(title)}</h1>"
        f'<p class="sub">{esc(subtitle or COVER_FALLBACK)}</p>'
        '<span class="n">1</span></section>'
    ]
    for i, section in enumerate(sections, start=2):
        bullets = "".join(f"<li>{esc(b)}</li>" for b in section.bullets)
        notes = f'<p class="notes">{esc(section.notes)}</p>' if section.notes else ""
        cards.append(
            f'<section class="slide"><h2>{esc(section.heading)}</h2>'
            f'{f"<ul>{bullets}</ul>" if bullets else ""}{notes}<span class="n">{i}</span></section>'
        )
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"<title>{esc(title)} — pitch deck</title>"
        "<style>"
        ":root{color-scheme:light}"
        "body{font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;margin:0;background:#0f1115;color:#e8eaed}"
        "header{max-width:60rem;margin:0 auto;padding:2.5rem 1.5rem 1rem}"
        "header h1{font-size:1.6rem;margin:0 0 .3rem}header p{margin:.2rem 0;color:#9aa0a6}"
        ".dl{display:inline-block;margin-top:1rem;padding:.55rem 1rem;border-radius:8px;background:#3b7dfc;"
        "color:#fff;text-decoration:none;font-weight:600}"
        "main{max-width:60rem;margin:0 auto;padding:1rem 1.5rem 4rem;display:grid;gap:1.25rem}"
        ".slide{position:relative;aspect-ratio:16/9;background:#fff;color:#16181d;border-radius:12px;"
        "padding:2.2rem 2.6rem;box-shadow:0 8px 24px rgba(0,0,0,.35);overflow:hidden}"
        ".slide h2{font-size:1.5rem;margin:0 0 1rem}"
        ".slide ul{margin:0;padding-left:1.2rem}.slide li{margin:.45rem 0}"
        ".cover{display:flex;flex-direction:column;justify-content:center;background:#16181d;color:#fff}"
        ".cover h1{font-size:2.2rem;margin:0 0 .6rem}.cover .sub{color:#c3c7cc;margin:0}"
        ".notes{margin-top:1rem;color:#5f6368;font-size:.9rem;font-style:italic}"
        ".n{position:absolute;right:1.1rem;bottom:.9rem;color:#9aa0a6;font-size:.8rem}"
        "</style></head><body>"
        f"<header><h1>{esc(title)}</h1><p>{esc(subtitle or 'Generated by Dayflow')}</p>"
        f"<p>{len(sections) + 1} slides · 16:9</p>"
        f'<a class="dl" href="{esc(pptx_url)}" download>Download .pptx</a></header>'
        f"<main>{''.join(cards)}</main></body></html>"
    )


# ---------- storage ----------


def pptx_key(page_id: str) -> str:
    return f"pages/deck/{page_id}.pptx"


async def store_pptx(page_id: str, data: bytes, pages: PageStore | None = None) -> None:
    await (pages or default_pages()).blobs.put(pptx_key(page_id), data, PPTX_MIME)


async def load_pptx(page_id: str, pages: PageStore | None = None) -> bytes | None:
    store = pages or default_pages()
    if not store.valid_id(page_id):
        return None
    return await store.blobs.get(pptx_key(page_id))


# ---------- tool ----------


async def build_deck(title: str, outline: list[dict[str, Any]], subtitle: str = "") -> dict:
    """Builds a real 16:9 PowerPoint deck (.pptx) and an HTML preview of it, both served by the brain.
    The deck gets a title slide plus ONE slide per outline entry, so pass at least 5 entries (8 is the
    usual pitch shape: problem, users, solution, demo, architecture, progress, plan, ask).
    Returns {id, preview_url, pptx_url, slides}: save the file to the vault with
    download(url=pptx_url, path="<repo>/pitch/<name>.pptx") and show the user open_tab(preview_url).

    Args:
        title: Deck title, e.g. "Dayflow — diploma project".
        outline: Ordered slides as [{"heading": "Problem", "bullets": ["...", "..."], "notes": "optional"}].
            2–5 short bullets per slide (a phrase each, not a paragraph); notes is optional speaker text.
        subtitle: One line under the title on the cover slide, e.g. the repo name and the date.
    """
    if not title.strip():
        return {"status": "error", "error": "title is empty — pass the deck title"}
    try:
        sections = normalize_outline(list(outline))
    except (ValueError, ValidationError) as e:
        return {"status": "error", "error": f"invalid outline: {e}"}
    if len(sections) < MIN_SECTIONS:
        return {
            "status": "error",
            "error": f"outline has {len(sections)} slides; pass at least {MIN_SECTIONS} "
            f"(the deck needs ≥{MIN_SECTIONS + 1} slides with the title slide) — 8 sections is the usual pitch.",
        }
    if len(sections) > MAX_SECTIONS:
        return {"status": "error", "error": f"outline has {len(sections)} slides; keep it under {MAX_SECTIONS}"}
    empty = [s.heading for s in sections if not s.bullets]
    data = build_pptx(title.strip(), subtitle.strip(), sections)

    pages = default_pages()
    # The preview links the .pptx, whose URL is the page's own URL + ".pptx" — so the id has to exist before
    # the HTML is rendered: put() reserves it, then the rendered page replaces the placeholder body.
    page = await pages.put("deck", "")
    pptx_url = f"{page['url']}.pptx"
    html_page = render_preview_html(title.strip(), subtitle.strip(), sections, pptx_url)
    await pages.blobs.put(PageStore._key("deck", page["id"]), html_page.encode(), "text/html; charset=utf-8")
    await store_pptx(page["id"], data, pages)
    return {
        "status": "success",
        "id": page["id"],
        "slides": len(sections) + 1,
        "bytes": len(data),
        "file_name": "diploma-pitch.pptx",
        "preview_url": page["url"],
        "pptx_url": pptx_url,
        "headings": [s.heading for s in sections],
        **({"warning": f"slides without bullets: {empty}"} if empty else {}),
        "next": "download(url=pptx_url, path='<repo>/pitch/diploma-pitch.pptx') to save the deck in the vault, "
        "download(url=preview_url, path='<repo>/pitch/diploma-pitch.html') to keep the preview, "
        "then open_tab(preview_url) to show it.",
    }


DECK_TOOLS = [build_deck]
